/** Schema namespace: `s.string()`, `s.object()`, ... and `s.Infer<...>`. */
export * as s from "./s.js";

export { err, isOutcome, matchOutcome, ok } from "./outcome.js";
export type { Failure, Outcome, Success } from "./outcome.js";

export { SchemaValidationError } from "./schema.js";
export type {
  BrandedId,
  Infer,
  LiteralValue,
  NumberOptions,
  ObjectOutput,
  ObjectSchema,
  OptionalSchema,
  ParseFailure,
  ParseResult,
  ParseSuccess,
  RefinementOptions,
  Schema,
  SchemaDescription,
  SchemaIssue,
  SchemaIssueCode,
  SchemaPathSegment,
  SchemaShape,
  StringOptions,
  TupleOutput,
} from "./schema.js";

export {
  command,
  event,
  feature,
  port,
  FAIL_RESULT,
  query,
  subscription,
} from "./descriptors.js";
export type {
  AdapterCallOptions,
  AdapterHandler,
  AdapterHooks,
  AnyBoundOperation,
  AnyFeature,
  AnyPort,
  AnyPortOperation,
  AnyUnboundOperation,
  AuthoredHttp,
  BindOperations,
  BoundOperation,
  BoundPortAdapter,
  BoundPortOperations,
  CommandDefinition,
  DeclaredError,
  EffectContext,
  EffectHandler,
  EffectKind,
  EffectMap,
  EnsureContext,
  EnsuresMap,
  ErrorConfig,
  ErrorDetails,
  ErrorSpec,
  ErrorSpecMap,
  EventDescriptor,
  EventEmitter,
  EventMap,
  ExecuteResult,
  ExecutionContext,
  FailFn,
  FeatureDescriptor,
  HttpMetadata,
  HttpMethod,
  MaybePromise,
  OperationEnsure,
  OperationFailure,
  PortDescriptor,
  PortFactory,
  PortImplementation,
  PortOperationDescriptor,
  PortOperationFactory,
  QueryDefinition,
  StoreOperations,
  StorePort,
  StorePortOptions,
  StoreShape,
  Subscription,
  SubscriptionContext,
  UnboundOperation,
  UnboundPortOperation,
  ValidOperations,
  ValidPortOps,
  WithoutWriteEffects,
} from "./descriptors.js";

export {
  ApplicationDefinitionError,
  authorize,
  createApplication,
  DispatchError,
  principal,
} from "./application.js";
export type {
  Application,
  ApplicationDefinition,
  ApplicationDefinitionIssue,
  ApplicationDefinitionIssueCode,
  ApplicationOperations,
  CallOptions,
  CompletedDispatch,
  DispatchFaultCode,
  DispatchFaultError,
  DispatchObserver,
  DispatchOptions,
  DispatchRejectionError,
  DispatchResult,
  EffectTraceEntry,
  EmittedEvent,
  EventTraceEntry,
  ExecutionTrace,
  FaultedDispatch,
  InvalidInputError,
  OperationsRecordOf,
  OpError,
  OpInput,
  OpOutput,
  PermissionDeniedError,
  Principal,
  RejectedDispatch,
  RuntimeMode,
  TraceEntry,
  UnionToIntersection,
  UnknownOperationError,
} from "./application.js";
